In [1]:
import numpy as np

In [2]:
np.random.seed(seed=24)

In [3]:
random_integers = np.random.randint(low=1, high=5, size=100)

In [8]:
random_integers[:10]

array([3, 4, 1, 4, 2, 2, 2, 1, 4, 4])

In [9]:
is_equal_to_3 = random_integers == 3

In [10]:
is_equal_to_3[:5]

array([ True, False, False, False, False])

In [11]:
sum(is_equal_to_3)

22

In [12]:
random_integers[is_equal_to_3]

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])